POST http://localhost:3001/api/cursos/programacion HTTP/1.1
Content-Type: application/json 

{
    "id": 4,
    "titulo": "Aprende Node.js",
    "lenguaje": "javascript",
    "vistas": 12312,
    "nivel": "basico"
}

###

PUT http://localhost:3001/api/cursos/programacion/3 HTTP/1.1
Content-Type:  application/json

{
    "id": 2,
    "titulo": "Python intermedio con proyectos",
    "lenguaje": "python",
    "vistas": 123123,
    "nivel": "intermedio"
}

###

PATCH http://localhost:3001/api/cursos/programacion/3 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Python intermedio con proyectos",
    "vistas": 12376
}